### ISSUE TITLE
登录不好使。

### ISSUE THREAD

**Issue by xndxcsd** [swumao/swuwifi#1]
退出好使，登录不好使。是用户名和密码没办法保存么。

**Comment by swumao** [comment]
用户名和密码保存在浏览器本地的，在选项里面进行设置。
登录时由于网络情况可能有swu_wifi或swu_wifi_dorm两种，所以要发两个请求可能有时候会有问题。

还有就是login.swu.edu.cn在学校不同地方解析到的IP地址不一样

**Comment by swumao** [comment]
已经解决登陆不好使的问题！ @xndxcsd
